export {default as HomePage} from './Home/Home'
export {default as ItemDetailPage} from './ItemDetail/ItemDetail'
export {default as ServicesPage} from './Services/Services'
export {default as AboutPage} from './About/About'
export {default as ProductsPage} from './Products/Products'
export {default as CartPage} from './Cart/Cart'
export {default as CategoryPage} from './Category/Category'